### PR TITLE
Less futzing for obj-see apps

### PR DESCRIPTION
**Pull request by arubdesu**
There's now a JSON feed for download locations, versions, descriptions, and (in some cases) formats(zip, dmg, pkg, etc.) so we don't need to URLTextSearch for the link anymore! Pardon the whitespace tweaking in the recipe I converted to using this processor, please give it a spin and let me know if I should update the other apps as well.

### CODE REVIEW

**Comment by arubdesu** [comment]
Note that the easiest way to test a new custom processor (although I've implemented the directory structure to allow it to work as-is, and potentially be shared across repos) is to move it into the same folder as the recipe that leverages it and modify the naming of the processor to just use the filename. An example is in the first commit on this PR.

**Comment by jps3** [comment]
I just saw the tweet about the JSON feed yesterday, but had not had a chance to follow up. Thank you so much for the code and pull request. I had been waiting for Objective-See to add flexibility like this to their offerings. Excellent!

**Comment by jps3** [comment]
Any thoughts at this time how to better handle the *.munki.recipe files going forward? The example of RansomWhere demonstrates it can provide zip, pkg or dmg (of pkg file). On first examination, this appears to make the munki recipes a bit more complicated because of the additional processor steps required for dealing with ZIP files vs DMG or PKG, no?

If ZIP is downloaded, it contains RansomWhere.app installer wrapper-app, which is what was used originally. The munki recipe as it currently stands (581d11592eabca33a744c4496a23037977bbc2e3) will unzip that *.app and stuff it into a DMG file, and the munki pkginfo file contains `preinstall_script` and `postinstall_script` which call the `RansomWhere` binary with `-install` or `-uninstall` flags as appropriate.

However, if a PKG or DMG are downloaded that obviates the need for any unzip-then-stuff-dmg processors, or the addition of those pkginfo `*_script`s. I am unsure at present how to best handle this in a clean, non-convoluted manner. 

Maybe I'm missing something stupidly obvious?

At present, most of the Objective-See offerings are still only ZIP files, but as the other formats may be added at any time.

Just curious if any ideas had occurred to you about this aspect of Objective See's new JSON update reporting.

**Comment by arubdesu** [comment]
I also asked about vanilla pkg installers that do the right thing [here in MacAdmins Slack](https://macadmins.slack.com/archives/security/p1481228688000390), but more pressingly we should rename this custom processor, even though it's only in your namespace. https://macadmins.slack.com/archives/autopkg/p1482407404002549
It's not truly generically able to handle any JSON feed or have a small/flexible enough scope to do what the name would lead people to believe it does

**Pull request merged**
